<?xml version="1.0"?>
<package format="3">
  <name>ur5e_gal2_actions</name>
  <version>0.0.0</version>
  <description>MoveIt actions node for UR5e + GAL2 (and arm-only via params)</description>

  <maintainer email="user@todo.todo">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>moveit_ros_planning_interface</depend>
  <depend>moveit_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_geometry_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

